### ISSUE TITLE
As a user, I should be able to view device logs

### ISSUE THREAD

**Issue by vdiezel** [ospin-web-dev/REACTor#411]
### Deliverables
 - [ ] investigate existing react packages for viewing logs. Please provide screenshots/links in this ticket here

As a user on the devices page:
  - [ ] I should be able to navigate to the device's logs in a separate view
As a user on the device logs page:
  - [ ] I should experience a 'loading' while the device logs are fetched (for the MVP, please don't worry about caching, or providing real time push updates)

----

#### Blocked By:

ospin-web-dev/hambda#36
(but dev can start on it at any time!)
