### ISSUE TITLE
Sensor boundaries should be set-able (min/max). an alert should be triggered if the sensor boundary is exceeded

### ISSUE THREAD

**Issue by DanielSeehausen** [ospin-web-dev/REACTor#519]
3- [ ] determine what the hambda ticket and its specs are required for this and create it
- [x] Downstreams can be given a min/max value
- [x] this value is both sent to the device with the process description AND persisted in the backend (on process description?)
- [x] As a user, during a running process, if a min/max value is reached, i should see an alert
- [x] SPIKE into displaying min/max lines on the graphs (see datadog for example). If easy and reasonable, create a new detailed user story of what the experience should be
